---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-deployment
  labels:
    app: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: <container_name>
        image: <image:latest>
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: model-service
      imagePullSecrets:
      - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: model-service-service
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  ---
  apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
type: Opaque
data:
  apiUrl: <docker_registry_api_url>
  username: <docker_registry_username>
  password: <docker_registry_password>
